// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsLayrzBle(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashLayrzBle(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsLayrzBle(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsLayrzBle(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsLayrzBle(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsLayrzBle(lhsKey, rhsKey) {
          if deepEqualsLayrzBle(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsLayrzBle(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashLayrzBle(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashLayrzBle(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashLayrzBle(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashLayrzBle(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashLayrzBle(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashLayrzBle(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct BtStatus: Hashable {
  var advertising: Bool
  var scanning: Bool
  var isEnabled: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BtStatus? {
    let advertising = pigeonVar_list[0] as! Bool
    let scanning = pigeonVar_list[1] as! Bool
    let isEnabled = pigeonVar_list[2] as! Bool

    return BtStatus(
      advertising: advertising,
      scanning: scanning,
      isEnabled: isEnabled
    )
  }
  func toList() -> [Any?] {
    return [
      advertising,
      scanning,
      isEnabled,
    ]
  }
  static func == (lhs: BtStatus, rhs: BtStatus) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzBle(lhs.advertising, rhs.advertising) && deepEqualsLayrzBle(lhs.scanning, rhs.scanning) && deepEqualsLayrzBle(lhs.isEnabled, rhs.isEnabled)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BtStatus")
    deepHashLayrzBle(value: advertising, hasher: &hasher)
    deepHashLayrzBle(value: scanning, hasher: &hasher)
    deepHashLayrzBle(value: isEnabled, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BtDevice: Hashable {
  var macAddress: String
  var name: String? = nil
  var rssi: Int64? = nil
  var txPower: Int64? = nil
  var manufacturerData: [BtManufacturerData]
  var serviceData: [BtServiceData]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BtDevice? {
    let macAddress = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let rssi: Int64? = nilOrValue(pigeonVar_list[2])
    let txPower: Int64? = nilOrValue(pigeonVar_list[3])
    let manufacturerData = pigeonVar_list[4] as! [BtManufacturerData]
    let serviceData = pigeonVar_list[5] as! [BtServiceData]

    return BtDevice(
      macAddress: macAddress,
      name: name,
      rssi: rssi,
      txPower: txPower,
      manufacturerData: manufacturerData,
      serviceData: serviceData
    )
  }
  func toList() -> [Any?] {
    return [
      macAddress,
      name,
      rssi,
      txPower,
      manufacturerData,
      serviceData,
    ]
  }
  static func == (lhs: BtDevice, rhs: BtDevice) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzBle(lhs.macAddress, rhs.macAddress) && deepEqualsLayrzBle(lhs.name, rhs.name) && deepEqualsLayrzBle(lhs.rssi, rhs.rssi) && deepEqualsLayrzBle(lhs.txPower, rhs.txPower) && deepEqualsLayrzBle(lhs.manufacturerData, rhs.manufacturerData) && deepEqualsLayrzBle(lhs.serviceData, rhs.serviceData)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BtDevice")
    deepHashLayrzBle(value: macAddress, hasher: &hasher)
    deepHashLayrzBle(value: name, hasher: &hasher)
    deepHashLayrzBle(value: rssi, hasher: &hasher)
    deepHashLayrzBle(value: txPower, hasher: &hasher)
    deepHashLayrzBle(value: manufacturerData, hasher: &hasher)
    deepHashLayrzBle(value: serviceData, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BtManufacturerData: Hashable {
  var companyId: Int64
  var data: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BtManufacturerData? {
    let companyId = pigeonVar_list[0] as! Int64
    let data: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])

    return BtManufacturerData(
      companyId: companyId,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      companyId,
      data,
    ]
  }
  static func == (lhs: BtManufacturerData, rhs: BtManufacturerData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzBle(lhs.companyId, rhs.companyId) && deepEqualsLayrzBle(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BtManufacturerData")
    deepHashLayrzBle(value: companyId, hasher: &hasher)
    deepHashLayrzBle(value: data, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BtServiceData: Hashable {
  var uuid: Int64
  var data: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BtServiceData? {
    let uuid = pigeonVar_list[0] as! Int64
    let data: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])

    return BtServiceData(
      uuid: uuid,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      data,
    ]
  }
  static func == (lhs: BtServiceData, rhs: BtServiceData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzBle(lhs.uuid, rhs.uuid) && deepEqualsLayrzBle(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BtServiceData")
    deepHashLayrzBle(value: uuid, hasher: &hasher)
    deepHashLayrzBle(value: data, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BtService: Hashable {
  var uuid: String
  var characteristics: [BtCharacteristic]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BtService? {
    let uuid = pigeonVar_list[0] as! String
    let characteristics = pigeonVar_list[1] as! [BtCharacteristic]

    return BtService(
      uuid: uuid,
      characteristics: characteristics
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      characteristics,
    ]
  }
  static func == (lhs: BtService, rhs: BtService) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzBle(lhs.uuid, rhs.uuid) && deepEqualsLayrzBle(lhs.characteristics, rhs.characteristics)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BtService")
    deepHashLayrzBle(value: uuid, hasher: &hasher)
    deepHashLayrzBle(value: characteristics, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BtCharacteristic: Hashable {
  var uuid: String
  var properties: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BtCharacteristic? {
    let uuid = pigeonVar_list[0] as! String
    let properties = pigeonVar_list[1] as! [String]

    return BtCharacteristic(
      uuid: uuid,
      properties: properties
    )
  }
  func toList() -> [Any?] {
    return [
      uuid,
      properties,
    ]
  }
  static func == (lhs: BtCharacteristic, rhs: BtCharacteristic) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzBle(lhs.uuid, rhs.uuid) && deepEqualsLayrzBle(lhs.properties, rhs.properties)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BtCharacteristic")
    deepHashLayrzBle(value: uuid, hasher: &hasher)
    deepHashLayrzBle(value: properties, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BtCharacteristicNotification: Hashable {
  var macAddress: String
  var serviceUuid: String
  var characteristicUuid: String
  var value: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BtCharacteristicNotification? {
    let macAddress = pigeonVar_list[0] as! String
    let serviceUuid = pigeonVar_list[1] as! String
    let characteristicUuid = pigeonVar_list[2] as! String
    let value = pigeonVar_list[3] as! FlutterStandardTypedData

    return BtCharacteristicNotification(
      macAddress: macAddress,
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      macAddress,
      serviceUuid,
      characteristicUuid,
      value,
    ]
  }
  static func == (lhs: BtCharacteristicNotification, rhs: BtCharacteristicNotification) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzBle(lhs.macAddress, rhs.macAddress) && deepEqualsLayrzBle(lhs.serviceUuid, rhs.serviceUuid) && deepEqualsLayrzBle(lhs.characteristicUuid, rhs.characteristicUuid) && deepEqualsLayrzBle(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BtCharacteristicNotification")
    deepHashLayrzBle(value: macAddress, hasher: &hasher)
    deepHashLayrzBle(value: serviceUuid, hasher: &hasher)
    deepHashLayrzBle(value: characteristicUuid, hasher: &hasher)
    deepHashLayrzBle(value: value, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BtGattReadRequest: Hashable {
  var macAddress: String
  var requestId: Int64
  var offset: Int64
  var serviceUuid: String
  var characteristicUuid: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BtGattReadRequest? {
    let macAddress = pigeonVar_list[0] as! String
    let requestId = pigeonVar_list[1] as! Int64
    let offset = pigeonVar_list[2] as! Int64
    let serviceUuid = pigeonVar_list[3] as! String
    let characteristicUuid = pigeonVar_list[4] as! String

    return BtGattReadRequest(
      macAddress: macAddress,
      requestId: requestId,
      offset: offset,
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid
    )
  }
  func toList() -> [Any?] {
    return [
      macAddress,
      requestId,
      offset,
      serviceUuid,
      characteristicUuid,
    ]
  }
  static func == (lhs: BtGattReadRequest, rhs: BtGattReadRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzBle(lhs.macAddress, rhs.macAddress) && deepEqualsLayrzBle(lhs.requestId, rhs.requestId) && deepEqualsLayrzBle(lhs.offset, rhs.offset) && deepEqualsLayrzBle(lhs.serviceUuid, rhs.serviceUuid) && deepEqualsLayrzBle(lhs.characteristicUuid, rhs.characteristicUuid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BtGattReadRequest")
    deepHashLayrzBle(value: macAddress, hasher: &hasher)
    deepHashLayrzBle(value: requestId, hasher: &hasher)
    deepHashLayrzBle(value: offset, hasher: &hasher)
    deepHashLayrzBle(value: serviceUuid, hasher: &hasher)
    deepHashLayrzBle(value: characteristicUuid, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BtGattWriteRequest: Hashable {
  var macAddress: String
  var requestId: Int64
  var offset: Int64
  var serviceUuid: String
  var characteristicUuid: String
  var data: FlutterStandardTypedData? = nil
  var preparedWrite: Bool
  var responseNeeded: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BtGattWriteRequest? {
    let macAddress = pigeonVar_list[0] as! String
    let requestId = pigeonVar_list[1] as! Int64
    let offset = pigeonVar_list[2] as! Int64
    let serviceUuid = pigeonVar_list[3] as! String
    let characteristicUuid = pigeonVar_list[4] as! String
    let data: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[5])
    let preparedWrite = pigeonVar_list[6] as! Bool
    let responseNeeded = pigeonVar_list[7] as! Bool

    return BtGattWriteRequest(
      macAddress: macAddress,
      requestId: requestId,
      offset: offset,
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid,
      data: data,
      preparedWrite: preparedWrite,
      responseNeeded: responseNeeded
    )
  }
  func toList() -> [Any?] {
    return [
      macAddress,
      requestId,
      offset,
      serviceUuid,
      characteristicUuid,
      data,
      preparedWrite,
      responseNeeded,
    ]
  }
  static func == (lhs: BtGattWriteRequest, rhs: BtGattWriteRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzBle(lhs.macAddress, rhs.macAddress) && deepEqualsLayrzBle(lhs.requestId, rhs.requestId) && deepEqualsLayrzBle(lhs.offset, rhs.offset) && deepEqualsLayrzBle(lhs.serviceUuid, rhs.serviceUuid) && deepEqualsLayrzBle(lhs.characteristicUuid, rhs.characteristicUuid) && deepEqualsLayrzBle(lhs.data, rhs.data) && deepEqualsLayrzBle(lhs.preparedWrite, rhs.preparedWrite) && deepEqualsLayrzBle(lhs.responseNeeded, rhs.responseNeeded)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BtGattWriteRequest")
    deepHashLayrzBle(value: macAddress, hasher: &hasher)
    deepHashLayrzBle(value: requestId, hasher: &hasher)
    deepHashLayrzBle(value: offset, hasher: &hasher)
    deepHashLayrzBle(value: serviceUuid, hasher: &hasher)
    deepHashLayrzBle(value: characteristicUuid, hasher: &hasher)
    deepHashLayrzBle(value: data, hasher: &hasher)
    deepHashLayrzBle(value: preparedWrite, hasher: &hasher)
    deepHashLayrzBle(value: responseNeeded, hasher: &hasher)
  }
}

private class LayrzBlePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return BtStatus.fromList(self.readValue() as! [Any?])
    case 130:
      return BtDevice.fromList(self.readValue() as! [Any?])
    case 131:
      return BtManufacturerData.fromList(self.readValue() as! [Any?])
    case 132:
      return BtServiceData.fromList(self.readValue() as! [Any?])
    case 133:
      return BtService.fromList(self.readValue() as! [Any?])
    case 134:
      return BtCharacteristic.fromList(self.readValue() as! [Any?])
    case 135:
      return BtCharacteristicNotification.fromList(self.readValue() as! [Any?])
    case 136:
      return BtGattReadRequest.fromList(self.readValue() as! [Any?])
    case 137:
      return BtGattWriteRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LayrzBlePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BtStatus {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? BtDevice {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? BtManufacturerData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? BtServiceData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? BtService {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? BtCharacteristic {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? BtCharacteristicNotification {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? BtGattReadRequest {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? BtGattWriteRequest {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LayrzBlePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LayrzBlePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LayrzBlePigeonCodecWriter(data: data)
  }
}

class LayrzBlePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LayrzBlePigeonCodec(readerWriter: LayrzBlePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LayrzBlePlatformChannel {
  func getStatuses(completion: @escaping (Result<BtStatus, Error>) -> Void)
  func checkCapabilities(completion: @escaping (Result<Bool, Error>) -> Void)
  func checkScanPermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  func checkAdvertisePermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  func startScan(macAddress: String?, servicesUuids: [String]?, completion: @escaping (Result<Bool, Error>) -> Void)
  func stopScan(macAddress: String?, completion: @escaping (Result<Bool, Error>) -> Void)
  func connect(macAddress: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func disconnect(macAddress: String?, completion: @escaping (Result<Bool, Error>) -> Void)
  func setMtu(macAddress: String, newMtu: Int64, completion: @escaping (Result<Int64?, Error>) -> Void)
  func discoverServices(macAddress: String, completion: @escaping (Result<[BtService], Error>) -> Void)
  func readCharacteristic(macAddress: String, serviceUuid: String, characteristicUuid: String, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  func writeCharacteristic(macAddress: String, serviceUuid: String, characteristicUuid: String, payload: FlutterStandardTypedData, withResponse: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func startNotify(macAddress: String, serviceUuid: String, characteristicUuid: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func stopNotify(macAddress: String, serviceUuid: String, characteristicUuid: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func startAdvertise(manufacturerData: [BtManufacturerData], serviceData: [BtServiceData], canConnect: Bool, name: String?, servicesSpecs: [BtService], allowBluetooth5: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func stopAdvertise(completion: @escaping (Result<Bool, Error>) -> Void)
  func respondReadRequest(requestId: Int64, macAddress: String, offset: Int64, data: FlutterStandardTypedData?, completion: @escaping (Result<Bool, Error>) -> Void)
  func respondWriteRequest(requestId: Int64, macAddress: String, offset: Int64, success: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func sendNotification(serviceUuid: String, characteristicUuid: String, payload: FlutterStandardTypedData, requestConfirmation: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func openBluetoothSettings(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LayrzBlePlatformChannelSetup {
  static var codec: FlutterStandardMessageCodec { LayrzBlePigeonCodec.shared }
  /// Sets up an instance of `LayrzBlePlatformChannel` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LayrzBlePlatformChannel?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getStatusesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.getStatuses\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStatusesChannel.setMessageHandler { _, reply in
        api.getStatuses { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getStatusesChannel.setMessageHandler(nil)
    }
    let checkCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkCapabilitiesChannel.setMessageHandler { _, reply in
        api.checkCapabilities { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkCapabilitiesChannel.setMessageHandler(nil)
    }
    let checkScanPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkScanPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkScanPermissionsChannel.setMessageHandler { _, reply in
        api.checkScanPermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkScanPermissionsChannel.setMessageHandler(nil)
    }
    let checkAdvertisePermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkAdvertisePermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkAdvertisePermissionsChannel.setMessageHandler { _, reply in
        api.checkAdvertisePermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkAdvertisePermissionsChannel.setMessageHandler(nil)
    }
    let startScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.startScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let macAddressArg: String? = nilOrValue(args[0])
        let servicesUuidsArg: [String]? = nilOrValue(args[1])
        api.startScan(macAddress: macAddressArg, servicesUuids: servicesUuidsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startScanChannel.setMessageHandler(nil)
    }
    let stopScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.stopScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let macAddressArg: String? = nilOrValue(args[0])
        api.stopScan(macAddress: macAddressArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopScanChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let macAddressArg = args[0] as! String
        api.connect(macAddress: macAddressArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let macAddressArg: String? = nilOrValue(args[0])
        api.disconnect(macAddress: macAddressArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let setMtuChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.setMtu\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMtuChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let macAddressArg = args[0] as! String
        let newMtuArg = args[1] as! Int64
        api.setMtu(macAddress: macAddressArg, newMtu: newMtuArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setMtuChannel.setMessageHandler(nil)
    }
    let discoverServicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.discoverServices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discoverServicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let macAddressArg = args[0] as! String
        api.discoverServices(macAddress: macAddressArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      discoverServicesChannel.setMessageHandler(nil)
    }
    let readCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.readCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let macAddressArg = args[0] as! String
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        api.readCharacteristic(macAddress: macAddressArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readCharacteristicChannel.setMessageHandler(nil)
    }
    let writeCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.writeCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let macAddressArg = args[0] as! String
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        let payloadArg = args[3] as! FlutterStandardTypedData
        let withResponseArg = args[4] as! Bool
        api.writeCharacteristic(macAddress: macAddressArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg, payload: payloadArg, withResponse: withResponseArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeCharacteristicChannel.setMessageHandler(nil)
    }
    let startNotifyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.startNotify\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startNotifyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let macAddressArg = args[0] as! String
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        api.startNotify(macAddress: macAddressArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startNotifyChannel.setMessageHandler(nil)
    }
    let stopNotifyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.stopNotify\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopNotifyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let macAddressArg = args[0] as! String
        let serviceUuidArg = args[1] as! String
        let characteristicUuidArg = args[2] as! String
        api.stopNotify(macAddress: macAddressArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopNotifyChannel.setMessageHandler(nil)
    }
    let startAdvertiseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.startAdvertise\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAdvertiseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let manufacturerDataArg = args[0] as! [BtManufacturerData]
        let serviceDataArg = args[1] as! [BtServiceData]
        let canConnectArg = args[2] as! Bool
        let nameArg: String? = nilOrValue(args[3])
        let servicesSpecsArg = args[4] as! [BtService]
        let allowBluetooth5Arg = args[5] as! Bool
        api.startAdvertise(manufacturerData: manufacturerDataArg, serviceData: serviceDataArg, canConnect: canConnectArg, name: nameArg, servicesSpecs: servicesSpecsArg, allowBluetooth5: allowBluetooth5Arg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startAdvertiseChannel.setMessageHandler(nil)
    }
    let stopAdvertiseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.stopAdvertise\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopAdvertiseChannel.setMessageHandler { _, reply in
        api.stopAdvertise { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopAdvertiseChannel.setMessageHandler(nil)
    }
    let respondReadRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.respondReadRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      respondReadRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        let macAddressArg = args[1] as! String
        let offsetArg = args[2] as! Int64
        let dataArg: FlutterStandardTypedData? = nilOrValue(args[3])
        api.respondReadRequest(requestId: requestIdArg, macAddress: macAddressArg, offset: offsetArg, data: dataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      respondReadRequestChannel.setMessageHandler(nil)
    }
    let respondWriteRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.respondWriteRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      respondWriteRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        let macAddressArg = args[1] as! String
        let offsetArg = args[2] as! Int64
        let successArg = args[3] as! Bool
        api.respondWriteRequest(requestId: requestIdArg, macAddress: macAddressArg, offset: offsetArg, success: successArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      respondWriteRequestChannel.setMessageHandler(nil)
    }
    let sendNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.sendNotification\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendNotificationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serviceUuidArg = args[0] as! String
        let characteristicUuidArg = args[1] as! String
        let payloadArg = args[2] as! FlutterStandardTypedData
        let requestConfirmationArg = args[3] as! Bool
        api.sendNotification(serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg, payload: payloadArg, requestConfirmation: requestConfirmationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendNotificationChannel.setMessageHandler(nil)
    }
    let openBluetoothSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.openBluetoothSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openBluetoothSettingsChannel.setMessageHandler { _, reply in
        api.openBluetoothSettings { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openBluetoothSettingsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LayrzBleCallbackChannelProtocol {
  func onScanResult(device deviceArg: BtDevice, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBluetoothOn(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBluetoothOff(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanStarted(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScanStopped(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onConnected(device deviceArg: BtDevice, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDisconnected(device deviceArg: BtDevice, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCharacteristicUpdate(notification notificationArg: BtCharacteristicNotification, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAdvertiseStarted(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAdvertiseStopped(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onGattConnected(device deviceArg: BtDevice, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onGattDisconnected(device deviceArg: BtDevice, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onGattReadRequest(request requestArg: BtGattReadRequest, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onGattWriteRequest(request requestArg: BtGattWriteRequest, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onGattMtuChanged(macAddress macAddressArg: String, newMtu newMtuArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class LayrzBleCallbackChannel: LayrzBleCallbackChannelProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: LayrzBlePigeonCodec {
    return LayrzBlePigeonCodec.shared
  }
  func onScanResult(device deviceArg: BtDevice, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBluetoothOn(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onBluetoothOn\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBluetoothOff(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onBluetoothOff\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanStarted(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScanStopped(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onConnected(device deviceArg: BtDevice, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onConnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onDisconnected(device deviceArg: BtDevice, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onDisconnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCharacteristicUpdate(notification notificationArg: BtCharacteristicNotification, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onCharacteristicUpdate\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([notificationArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAdvertiseStarted(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onAdvertiseStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAdvertiseStopped(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onAdvertiseStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onGattConnected(device deviceArg: BtDevice, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattConnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onGattDisconnected(device deviceArg: BtDevice, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattDisconnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onGattReadRequest(request requestArg: BtGattReadRequest, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattReadRequest\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onGattWriteRequest(request requestArg: BtGattWriteRequest, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattWriteRequest\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onGattMtuChanged(macAddress macAddressArg: String, newMtu newMtuArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattMtuChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([macAddressArg, newMtuArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
