name: layrz_ble
description: "A Flutter library for cross-platform Bluetooth Low Energy (BLE) communication, supporting Android, iOS, macOS, Windows, Linux, and web."
version: 1.3.3
repository: https://github.com/goldenm-software/layrz_ble

keywords:
  - bluetooth
  - ble
  - bluetooth low energy
  - flutter
  - cross-platform
  - device communication
  - android
  - ios
  - windows
  - macos
  - linux
  - web
  - GATT
  - wireless communication

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  web: ^1.1.0
  plugin_platform_interface: ^2.0.2
  collection: ^1.18.0
  layrz_models: ^3.4.0
  flutter_web_bluetooth: ^1.0.0
  bluez: ^0.8.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  pigeon: ^26.3.3
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.layrz.layrz_ble
        pluginClass: LayrzBlePlugin
      windows:
        pluginClass: LayrzBlePluginCApi
      ios:
        pluginClass: LayrzBlePlugin
        sharedDarwinSource: true
      macos:
        pluginClass: LayrzBlePlugin
        sharedDarwinSource: true

