// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class BtStatus {
  BtStatus({
    required this.advertising,
    required this.scanning,
  });

  bool advertising;

  bool scanning;

  List<Object?> _toList() {
    return <Object?>[
      advertising,
      scanning,
    ];
  }

  Object encode() {
    return _toList();  }

  static BtStatus decode(Object result) {
    result as List<Object?>;
    return BtStatus(
      advertising: result[0]! as bool,
      scanning: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BtStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class BtDevice {
  BtDevice({
    required this.macAddress,
    this.name,
    this.rssi,
    this.txPower,
    required this.manufacturerData,
    required this.serviceData,
  });

  String macAddress;

  String? name;

  int? rssi;

  int? txPower;

  List<BtManufacturerData> manufacturerData;

  List<BtServiceData> serviceData;

  List<Object?> _toList() {
    return <Object?>[
      macAddress,
      name,
      rssi,
      txPower,
      manufacturerData,
      serviceData,
    ];
  }

  Object encode() {
    return _toList();  }

  static BtDevice decode(Object result) {
    result as List<Object?>;
    return BtDevice(
      macAddress: result[0]! as String,
      name: result[1] as String?,
      rssi: result[2] as int?,
      txPower: result[3] as int?,
      manufacturerData: (result[4] as List<Object?>?)!.cast<BtManufacturerData>(),
      serviceData: (result[5] as List<Object?>?)!.cast<BtServiceData>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BtDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class BtManufacturerData {
  BtManufacturerData({
    required this.companyId,
    this.data,
  });

  int companyId;

  Uint8List? data;

  List<Object?> _toList() {
    return <Object?>[
      companyId,
      data,
    ];
  }

  Object encode() {
    return _toList();  }

  static BtManufacturerData decode(Object result) {
    result as List<Object?>;
    return BtManufacturerData(
      companyId: result[0]! as int,
      data: result[1] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BtManufacturerData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class BtServiceData {
  BtServiceData({
    required this.uuid,
    this.data,
  });

  int uuid;

  Uint8List? data;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      data,
    ];
  }

  Object encode() {
    return _toList();  }

  static BtServiceData decode(Object result) {
    result as List<Object?>;
    return BtServiceData(
      uuid: result[0]! as int,
      data: result[1] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BtServiceData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class BtService {
  BtService({
    required this.uuid,
    required this.characteristics,
  });

  String uuid;

  List<BtCharacteristic> characteristics;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      characteristics,
    ];
  }

  Object encode() {
    return _toList();  }

  static BtService decode(Object result) {
    result as List<Object?>;
    return BtService(
      uuid: result[0]! as String,
      characteristics: (result[1] as List<Object?>?)!.cast<BtCharacteristic>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BtService || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class BtCharacteristic {
  BtCharacteristic({
    required this.uuid,
    required this.properties,
  });

  String uuid;

  List<String> properties;

  List<Object?> _toList() {
    return <Object?>[
      uuid,
      properties,
    ];
  }

  Object encode() {
    return _toList();  }

  static BtCharacteristic decode(Object result) {
    result as List<Object?>;
    return BtCharacteristic(
      uuid: result[0]! as String,
      properties: (result[1] as List<Object?>?)!.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BtCharacteristic || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class BtCharacteristicNotification {
  BtCharacteristicNotification({
    required this.macAddress,
    required this.serviceUuid,
    required this.characteristicUuid,
    required this.value,
  });

  String macAddress;

  String serviceUuid;

  String characteristicUuid;

  Uint8List value;

  List<Object?> _toList() {
    return <Object?>[
      macAddress,
      serviceUuid,
      characteristicUuid,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static BtCharacteristicNotification decode(Object result) {
    result as List<Object?>;
    return BtCharacteristicNotification(
      macAddress: result[0]! as String,
      serviceUuid: result[1]! as String,
      characteristicUuid: result[2]! as String,
      value: result[3]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BtCharacteristicNotification || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class BtGattReadRequest {
  BtGattReadRequest({
    required this.macAddress,
    required this.requestId,
    required this.offset,
    required this.serviceUuid,
    required this.characteristicUuid,
  });

  String macAddress;

  int requestId;

  int offset;

  String serviceUuid;

  String characteristicUuid;

  List<Object?> _toList() {
    return <Object?>[
      macAddress,
      requestId,
      offset,
      serviceUuid,
      characteristicUuid,
    ];
  }

  Object encode() {
    return _toList();  }

  static BtGattReadRequest decode(Object result) {
    result as List<Object?>;
    return BtGattReadRequest(
      macAddress: result[0]! as String,
      requestId: result[1]! as int,
      offset: result[2]! as int,
      serviceUuid: result[3]! as String,
      characteristicUuid: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BtGattReadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class BtGattWriteRequest {
  BtGattWriteRequest({
    required this.macAddress,
    required this.requestId,
    required this.offset,
    required this.serviceUuid,
    required this.characteristicUuid,
    this.data,
    required this.preparedWrite,
    required this.responseNeeded,
  });

  String macAddress;

  int requestId;

  int offset;

  String serviceUuid;

  String characteristicUuid;

  Uint8List? data;

  bool preparedWrite;

  bool responseNeeded;

  List<Object?> _toList() {
    return <Object?>[
      macAddress,
      requestId,
      offset,
      serviceUuid,
      characteristicUuid,
      data,
      preparedWrite,
      responseNeeded,
    ];
  }

  Object encode() {
    return _toList();  }

  static BtGattWriteRequest decode(Object result) {
    result as List<Object?>;
    return BtGattWriteRequest(
      macAddress: result[0]! as String,
      requestId: result[1]! as int,
      offset: result[2]! as int,
      serviceUuid: result[3]! as String,
      characteristicUuid: result[4]! as String,
      data: result[5] as Uint8List?,
      preparedWrite: result[6]! as bool,
      responseNeeded: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BtGattWriteRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BtStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is BtDevice) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is BtManufacturerData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is BtServiceData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is BtService) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is BtCharacteristic) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is BtCharacteristicNotification) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is BtGattReadRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is BtGattWriteRequest) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return BtStatus.decode(readValue(buffer)!);
      case 130: 
        return BtDevice.decode(readValue(buffer)!);
      case 131: 
        return BtManufacturerData.decode(readValue(buffer)!);
      case 132: 
        return BtServiceData.decode(readValue(buffer)!);
      case 133: 
        return BtService.decode(readValue(buffer)!);
      case 134: 
        return BtCharacteristic.decode(readValue(buffer)!);
      case 135: 
        return BtCharacteristicNotification.decode(readValue(buffer)!);
      case 136: 
        return BtGattReadRequest.decode(readValue(buffer)!);
      case 137: 
        return BtGattWriteRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LayrzBlePlatformChannel {
  /// Constructor for [LayrzBlePlatformChannel].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LayrzBlePlatformChannel({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<BtStatus> getStatuses() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.getStatuses$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BtStatus?)!;
    }
  }

  Future<bool> checkCapabilities() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkCapabilities$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> checkScanPermissions() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkScanPermissions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> checkAdvertisePermissions() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkAdvertisePermissions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> startScan({String? macAddress, List<String>? servicesUuids}) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.startScan$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[macAddress, servicesUuids]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> stopScan({String? macAddress}) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.stopScan$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[macAddress]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> connect({required String macAddress}) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.connect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[macAddress]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> disconnect({String? macAddress}) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.disconnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[macAddress]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<int?> setMtu({required String macAddress, required int newMtu}) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.setMtu$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[macAddress, newMtu]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as int?);
    }
  }

  Future<List<BtService>> discoverServices({required String macAddress}) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.discoverServices$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[macAddress]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<BtService>();
    }
  }

  Future<Uint8List> readCharacteristic({required String macAddress, required String serviceUuid, required String characteristicUuid, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.readCharacteristic$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[macAddress, serviceUuid, characteristicUuid]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Uint8List?)!;
    }
  }

  Future<bool> writeCharacteristic({required String macAddress, required String serviceUuid, required String characteristicUuid, required Uint8List payload, required bool withResponse, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.writeCharacteristic$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[macAddress, serviceUuid, characteristicUuid, payload, withResponse]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> startNotify({required String macAddress, required String serviceUuid, required String characteristicUuid, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.startNotify$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[macAddress, serviceUuid, characteristicUuid]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> stopNotify({required String macAddress, required String serviceUuid, required String characteristicUuid, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.stopNotify$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[macAddress, serviceUuid, characteristicUuid]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> startAdvertise({List<BtManufacturerData> manufacturerData = const [], List<BtServiceData> serviceData = const [], bool canConnect = false, String? name, List<BtService> servicesSpecs = const [], bool allowBluetooth5 = true, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.startAdvertise$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[manufacturerData, serviceData, canConnect, name, servicesSpecs, allowBluetooth5]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> stopAdvertise() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.stopAdvertise$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> respondReadRequest({required int requestId, required String macAddress, required int offset, Uint8List? data, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.respondReadRequest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId, macAddress, offset, data]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> respondWriteRequest({required int requestId, required String macAddress, required int offset, required bool success, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.respondWriteRequest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId, macAddress, offset, success]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> sendNotification({required String serviceUuid, required String characteristicUuid, required Uint8List payload, bool requestConfirmation = false, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.sendNotification$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serviceUuid, characteristicUuid, payload, requestConfirmation]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

abstract class LayrzBleCallbackChannel {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onScanResult(BtDevice device);

  void onBluetoothOn();

  void onBluetoothOff();

  void onScanStarted();

  void onScanStopped();

  void onConnected(BtDevice device);

  void onDisconnected(BtDevice device);

  void onCharacteristicUpdate(BtCharacteristicNotification notification);

  void onAdvertiseStarted();

  void onAdvertiseStopped();

  void onGattConnected(BtDevice device);

  void onGattDisconnected(BtDevice device);

  void onGattReadRequest(BtGattReadRequest request);

  void onGattWriteRequest(BtGattWriteRequest request);

  void onGattMtuChanged(String macAddress, int newMtu);

  static void setUp(LayrzBleCallbackChannel? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanResult$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanResult was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BtDevice? arg_device = (args[0] as BtDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanResult was null, expected non-null BtDevice.');
          try {
            api.onScanResult(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onBluetoothOn$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onBluetoothOn();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onBluetoothOff$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onBluetoothOff();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanStarted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onScanStarted();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanStopped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onScanStopped();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onConnected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onConnected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BtDevice? arg_device = (args[0] as BtDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onConnected was null, expected non-null BtDevice.');
          try {
            api.onConnected(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onDisconnected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onDisconnected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BtDevice? arg_device = (args[0] as BtDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onDisconnected was null, expected non-null BtDevice.');
          try {
            api.onDisconnected(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onCharacteristicUpdate$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onCharacteristicUpdate was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BtCharacteristicNotification? arg_notification = (args[0] as BtCharacteristicNotification?);
          assert(arg_notification != null,
              'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onCharacteristicUpdate was null, expected non-null BtCharacteristicNotification.');
          try {
            api.onCharacteristicUpdate(arg_notification!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onAdvertiseStarted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onAdvertiseStarted();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onAdvertiseStopped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onAdvertiseStopped();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattConnected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattConnected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BtDevice? arg_device = (args[0] as BtDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattConnected was null, expected non-null BtDevice.');
          try {
            api.onGattConnected(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattDisconnected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattDisconnected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BtDevice? arg_device = (args[0] as BtDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattDisconnected was null, expected non-null BtDevice.');
          try {
            api.onGattDisconnected(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattReadRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattReadRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BtGattReadRequest? arg_request = (args[0] as BtGattReadRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattReadRequest was null, expected non-null BtGattReadRequest.');
          try {
            api.onGattReadRequest(arg_request!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattWriteRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattWriteRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BtGattWriteRequest? arg_request = (args[0] as BtGattWriteRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattWriteRequest was null, expected non-null BtGattWriteRequest.');
          try {
            api.onGattWriteRequest(arg_request!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattMtuChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattMtuChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_macAddress = (args[0] as String?);
          assert(arg_macAddress != null,
              'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattMtuChanged was null, expected non-null String.');
          final int? arg_newMtu = (args[1] as int?);
          assert(arg_newMtu != null,
              'Argument for dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattMtuChanged was null, expected non-null int.');
          try {
            api.onGattMtuChanged(arg_macAddress!, arg_newMtu!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
