// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.layrz.layrz_ble

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LayrzBlePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class BtStatus (
  val advertising: Boolean,
  val scanning: Boolean,
  val isEnabled: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtStatus {
      val advertising = pigeonVar_list[0] as Boolean
      val scanning = pigeonVar_list[1] as Boolean
      val isEnabled = pigeonVar_list[2] as Boolean
      return BtStatus(advertising, scanning, isEnabled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      advertising,
      scanning,
      isEnabled,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BtStatus
    return LayrzBlePigeonUtils.deepEquals(this.advertising, other.advertising) && LayrzBlePigeonUtils.deepEquals(this.scanning, other.scanning) && LayrzBlePigeonUtils.deepEquals(this.isEnabled, other.isEnabled)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.advertising)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.scanning)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.isEnabled)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtDevice (
  val macAddress: String,
  val name: String? = null,
  val rssi: Long? = null,
  val txPower: Long? = null,
  val manufacturerData: List<BtManufacturerData>,
  val serviceData: List<BtServiceData>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtDevice {
      val macAddress = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val rssi = pigeonVar_list[2] as Long?
      val txPower = pigeonVar_list[3] as Long?
      val manufacturerData = pigeonVar_list[4] as List<BtManufacturerData>
      val serviceData = pigeonVar_list[5] as List<BtServiceData>
      return BtDevice(macAddress, name, rssi, txPower, manufacturerData, serviceData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      macAddress,
      name,
      rssi,
      txPower,
      manufacturerData,
      serviceData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BtDevice
    return LayrzBlePigeonUtils.deepEquals(this.macAddress, other.macAddress) && LayrzBlePigeonUtils.deepEquals(this.name, other.name) && LayrzBlePigeonUtils.deepEquals(this.rssi, other.rssi) && LayrzBlePigeonUtils.deepEquals(this.txPower, other.txPower) && LayrzBlePigeonUtils.deepEquals(this.manufacturerData, other.manufacturerData) && LayrzBlePigeonUtils.deepEquals(this.serviceData, other.serviceData)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.macAddress)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.name)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.rssi)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.txPower)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.manufacturerData)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.serviceData)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtManufacturerData (
  val companyId: Long,
  val data: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtManufacturerData {
      val companyId = pigeonVar_list[0] as Long
      val data = pigeonVar_list[1] as ByteArray?
      return BtManufacturerData(companyId, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      companyId,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BtManufacturerData
    return LayrzBlePigeonUtils.deepEquals(this.companyId, other.companyId) && LayrzBlePigeonUtils.deepEquals(this.data, other.data)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.companyId)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.data)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtServiceData (
  val uuid: Long,
  val data: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtServiceData {
      val uuid = pigeonVar_list[0] as Long
      val data = pigeonVar_list[1] as ByteArray?
      return BtServiceData(uuid, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BtServiceData
    return LayrzBlePigeonUtils.deepEquals(this.uuid, other.uuid) && LayrzBlePigeonUtils.deepEquals(this.data, other.data)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.uuid)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.data)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtService (
  val uuid: String,
  val characteristics: List<BtCharacteristic>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtService {
      val uuid = pigeonVar_list[0] as String
      val characteristics = pigeonVar_list[1] as List<BtCharacteristic>
      return BtService(uuid, characteristics)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      characteristics,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BtService
    return LayrzBlePigeonUtils.deepEquals(this.uuid, other.uuid) && LayrzBlePigeonUtils.deepEquals(this.characteristics, other.characteristics)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.uuid)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.characteristics)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtCharacteristic (
  val uuid: String,
  val properties: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtCharacteristic {
      val uuid = pigeonVar_list[0] as String
      val properties = pigeonVar_list[1] as List<String>
      return BtCharacteristic(uuid, properties)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      properties,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BtCharacteristic
    return LayrzBlePigeonUtils.deepEquals(this.uuid, other.uuid) && LayrzBlePigeonUtils.deepEquals(this.properties, other.properties)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.uuid)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.properties)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtCharacteristicNotification (
  val macAddress: String,
  val serviceUuid: String,
  val characteristicUuid: String,
  val value: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtCharacteristicNotification {
      val macAddress = pigeonVar_list[0] as String
      val serviceUuid = pigeonVar_list[1] as String
      val characteristicUuid = pigeonVar_list[2] as String
      val value = pigeonVar_list[3] as ByteArray
      return BtCharacteristicNotification(macAddress, serviceUuid, characteristicUuid, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      macAddress,
      serviceUuid,
      characteristicUuid,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BtCharacteristicNotification
    return LayrzBlePigeonUtils.deepEquals(this.macAddress, other.macAddress) && LayrzBlePigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && LayrzBlePigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && LayrzBlePigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.macAddress)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.value)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtGattReadRequest (
  val macAddress: String,
  val requestId: Long,
  val offset: Long,
  val serviceUuid: String,
  val characteristicUuid: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtGattReadRequest {
      val macAddress = pigeonVar_list[0] as String
      val requestId = pigeonVar_list[1] as Long
      val offset = pigeonVar_list[2] as Long
      val serviceUuid = pigeonVar_list[3] as String
      val characteristicUuid = pigeonVar_list[4] as String
      return BtGattReadRequest(macAddress, requestId, offset, serviceUuid, characteristicUuid)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      macAddress,
      requestId,
      offset,
      serviceUuid,
      characteristicUuid,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BtGattReadRequest
    return LayrzBlePigeonUtils.deepEquals(this.macAddress, other.macAddress) && LayrzBlePigeonUtils.deepEquals(this.requestId, other.requestId) && LayrzBlePigeonUtils.deepEquals(this.offset, other.offset) && LayrzBlePigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && LayrzBlePigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.macAddress)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.requestId)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.offset)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.characteristicUuid)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtGattWriteRequest (
  val macAddress: String,
  val requestId: Long,
  val offset: Long,
  val serviceUuid: String,
  val characteristicUuid: String,
  val data: ByteArray? = null,
  val preparedWrite: Boolean,
  val responseNeeded: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtGattWriteRequest {
      val macAddress = pigeonVar_list[0] as String
      val requestId = pigeonVar_list[1] as Long
      val offset = pigeonVar_list[2] as Long
      val serviceUuid = pigeonVar_list[3] as String
      val characteristicUuid = pigeonVar_list[4] as String
      val data = pigeonVar_list[5] as ByteArray?
      val preparedWrite = pigeonVar_list[6] as Boolean
      val responseNeeded = pigeonVar_list[7] as Boolean
      return BtGattWriteRequest(macAddress, requestId, offset, serviceUuid, characteristicUuid, data, preparedWrite, responseNeeded)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      macAddress,
      requestId,
      offset,
      serviceUuid,
      characteristicUuid,
      data,
      preparedWrite,
      responseNeeded,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BtGattWriteRequest
    return LayrzBlePigeonUtils.deepEquals(this.macAddress, other.macAddress) && LayrzBlePigeonUtils.deepEquals(this.requestId, other.requestId) && LayrzBlePigeonUtils.deepEquals(this.offset, other.offset) && LayrzBlePigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && LayrzBlePigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && LayrzBlePigeonUtils.deepEquals(this.data, other.data) && LayrzBlePigeonUtils.deepEquals(this.preparedWrite, other.preparedWrite) && LayrzBlePigeonUtils.deepEquals(this.responseNeeded, other.responseNeeded)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.macAddress)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.requestId)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.offset)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.data)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.preparedWrite)
    result = 31 * result + LayrzBlePigeonUtils.deepHash(this.responseNeeded)
    return result
  }
}
private open class LayrzBlePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtStatus.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtDevice.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtManufacturerData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtServiceData.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtService.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtCharacteristic.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtCharacteristicNotification.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtGattReadRequest.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtGattWriteRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BtStatus -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BtDevice -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is BtManufacturerData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is BtServiceData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is BtService -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is BtCharacteristic -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BtCharacteristicNotification -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is BtGattReadRequest -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is BtGattWriteRequest -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LayrzBlePlatformChannel {
  fun getStatuses(callback: (Result<BtStatus>) -> Unit)
  fun checkCapabilities(callback: (Result<Boolean>) -> Unit)
  fun checkScanPermissions(callback: (Result<Boolean>) -> Unit)
  fun checkAdvertisePermissions(callback: (Result<Boolean>) -> Unit)
  fun startScan(macAddress: String?, servicesUuids: List<String>?, callback: (Result<Boolean>) -> Unit)
  fun stopScan(macAddress: String?, callback: (Result<Boolean>) -> Unit)
  fun connect(macAddress: String, callback: (Result<Boolean>) -> Unit)
  fun disconnect(macAddress: String?, callback: (Result<Boolean>) -> Unit)
  fun setMtu(macAddress: String, newMtu: Long, callback: (Result<Long?>) -> Unit)
  fun discoverServices(macAddress: String, callback: (Result<List<BtService>>) -> Unit)
  fun readCharacteristic(macAddress: String, serviceUuid: String, characteristicUuid: String, callback: (Result<ByteArray>) -> Unit)
  fun writeCharacteristic(macAddress: String, serviceUuid: String, characteristicUuid: String, payload: ByteArray, withResponse: Boolean, callback: (Result<Boolean>) -> Unit)
  fun startNotify(macAddress: String, serviceUuid: String, characteristicUuid: String, callback: (Result<Boolean>) -> Unit)
  fun stopNotify(macAddress: String, serviceUuid: String, characteristicUuid: String, callback: (Result<Boolean>) -> Unit)
  fun startAdvertise(manufacturerData: List<BtManufacturerData>, serviceData: List<BtServiceData>, canConnect: Boolean, name: String?, servicesSpecs: List<BtService>, allowBluetooth5: Boolean, callback: (Result<Boolean>) -> Unit)
  fun stopAdvertise(callback: (Result<Boolean>) -> Unit)
  fun respondReadRequest(requestId: Long, macAddress: String, offset: Long, data: ByteArray?, callback: (Result<Boolean>) -> Unit)
  fun respondWriteRequest(requestId: Long, macAddress: String, offset: Long, success: Boolean, callback: (Result<Boolean>) -> Unit)
  fun sendNotification(serviceUuid: String, characteristicUuid: String, payload: ByteArray, requestConfirmation: Boolean, callback: (Result<Boolean>) -> Unit)
  fun openBluetoothSettings(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by LayrzBlePlatformChannel. */
    val codec: MessageCodec<Any?> by lazy {
      LayrzBlePigeonCodec()
    }
    /** Sets up an instance of `LayrzBlePlatformChannel` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LayrzBlePlatformChannel?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.getStatuses$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getStatuses{ result: Result<BtStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkCapabilities{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkScanPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkScanPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkAdvertisePermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkAdvertisePermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String?
            val servicesUuidsArg = args[1] as List<String>?
            api.startScan(macAddressArg, servicesUuidsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.stopScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String?
            api.stopScan(macAddressArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            api.connect(macAddressArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String?
            api.disconnect(macAddressArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.setMtu$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            val newMtuArg = args[1] as Long
            api.setMtu(macAddressArg, newMtuArg) { result: Result<Long?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.discoverServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            api.discoverServices(macAddressArg) { result: Result<List<BtService>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.readCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            api.readCharacteristic(macAddressArg, serviceUuidArg, characteristicUuidArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.writeCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            val payloadArg = args[3] as ByteArray
            val withResponseArg = args[4] as Boolean
            api.writeCharacteristic(macAddressArg, serviceUuidArg, characteristicUuidArg, payloadArg, withResponseArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.startNotify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            api.startNotify(macAddressArg, serviceUuidArg, characteristicUuidArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.stopNotify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            api.stopNotify(macAddressArg, serviceUuidArg, characteristicUuidArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.startAdvertise$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val manufacturerDataArg = args[0] as List<BtManufacturerData>
            val serviceDataArg = args[1] as List<BtServiceData>
            val canConnectArg = args[2] as Boolean
            val nameArg = args[3] as String?
            val servicesSpecsArg = args[4] as List<BtService>
            val allowBluetooth5Arg = args[5] as Boolean
            api.startAdvertise(manufacturerDataArg, serviceDataArg, canConnectArg, nameArg, servicesSpecsArg, allowBluetooth5Arg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.stopAdvertise$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopAdvertise{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.respondReadRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val macAddressArg = args[1] as String
            val offsetArg = args[2] as Long
            val dataArg = args[3] as ByteArray?
            api.respondReadRequest(requestIdArg, macAddressArg, offsetArg, dataArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.respondWriteRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val macAddressArg = args[1] as String
            val offsetArg = args[2] as Long
            val successArg = args[3] as Boolean
            api.respondWriteRequest(requestIdArg, macAddressArg, offsetArg, successArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.sendNotification$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceUuidArg = args[0] as String
            val characteristicUuidArg = args[1] as String
            val payloadArg = args[2] as ByteArray
            val requestConfirmationArg = args[3] as Boolean
            api.sendNotification(serviceUuidArg, characteristicUuidArg, payloadArg, requestConfirmationArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.openBluetoothSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openBluetoothSettings{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class LayrzBleCallbackChannel(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LayrzBleCallbackChannel. */
    val codec: MessageCodec<Any?> by lazy {
      LayrzBlePigeonCodec()
    }
  }
  fun onScanResult(deviceArg: BtDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBluetoothOn(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onBluetoothOn$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBluetoothOff(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onBluetoothOff$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onScanStarted(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanStarted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onScanStopped(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanStopped$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onConnected(deviceArg: BtDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onConnected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDisconnected(deviceArg: BtDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onDisconnected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onCharacteristicUpdate(notificationArg: BtCharacteristicNotification, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onCharacteristicUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(notificationArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAdvertiseStarted(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onAdvertiseStarted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAdvertiseStopped(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onAdvertiseStopped$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onGattConnected(deviceArg: BtDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattConnected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onGattDisconnected(deviceArg: BtDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattDisconnected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onGattReadRequest(requestArg: BtGattReadRequest, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattReadRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onGattWriteRequest(requestArg: BtGattWriteRequest, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattWriteRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onGattMtuChanged(macAddressArg: String, newMtuArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onGattMtuChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(macAddressArg, newMtuArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
