// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.layrz.layrz_ble

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LayrzBlePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class BtStatus (
  val advertising: Boolean,
  val scanning: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtStatus {
      val advertising = pigeonVar_list[0] as Boolean
      val scanning = pigeonVar_list[1] as Boolean
      return BtStatus(advertising, scanning)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      advertising,
      scanning,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BtStatus) {
      return false
    }
    if (this === other) {
      return true
    }
    return LayrzBlePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtDevice (
  val macAddress: String,
  val name: String? = null,
  val rssi: Long? = null,
  val txPower: Long? = null,
  val manufacturerData: List<BtManufacturerData>,
  val serviceData: List<BtServiceData>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtDevice {
      val macAddress = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val rssi = pigeonVar_list[2] as Long?
      val txPower = pigeonVar_list[3] as Long?
      val manufacturerData = pigeonVar_list[4] as List<BtManufacturerData>
      val serviceData = pigeonVar_list[5] as List<BtServiceData>
      return BtDevice(macAddress, name, rssi, txPower, manufacturerData, serviceData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      macAddress,
      name,
      rssi,
      txPower,
      manufacturerData,
      serviceData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BtDevice) {
      return false
    }
    if (this === other) {
      return true
    }
    return LayrzBlePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtManufacturerData (
  val companyId: Long,
  val data: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtManufacturerData {
      val companyId = pigeonVar_list[0] as Long
      val data = pigeonVar_list[1] as ByteArray?
      return BtManufacturerData(companyId, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      companyId,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BtManufacturerData) {
      return false
    }
    if (this === other) {
      return true
    }
    return LayrzBlePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtServiceData (
  val uuid: Long,
  val data: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtServiceData {
      val uuid = pigeonVar_list[0] as Long
      val data = pigeonVar_list[1] as ByteArray?
      return BtServiceData(uuid, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BtServiceData) {
      return false
    }
    if (this === other) {
      return true
    }
    return LayrzBlePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtService (
  val uuid: String,
  val characteristics: List<BtCharacteristic>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtService {
      val uuid = pigeonVar_list[0] as String
      val characteristics = pigeonVar_list[1] as List<BtCharacteristic>
      return BtService(uuid, characteristics)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      characteristics,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BtService) {
      return false
    }
    if (this === other) {
      return true
    }
    return LayrzBlePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtCharacteristic (
  val uuid: String,
  val properties: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtCharacteristic {
      val uuid = pigeonVar_list[0] as String
      val properties = pigeonVar_list[1] as List<String>
      return BtCharacteristic(uuid, properties)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      properties,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BtCharacteristic) {
      return false
    }
    if (this === other) {
      return true
    }
    return LayrzBlePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BtCharacteristicNotification (
  val macAddress: String,
  val serviceUuid: String,
  val characteristicUuid: String,
  val value: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BtCharacteristicNotification {
      val macAddress = pigeonVar_list[0] as String
      val serviceUuid = pigeonVar_list[1] as String
      val characteristicUuid = pigeonVar_list[2] as String
      val value = pigeonVar_list[3] as ByteArray
      return BtCharacteristicNotification(macAddress, serviceUuid, characteristicUuid, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      macAddress,
      serviceUuid,
      characteristicUuid,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BtCharacteristicNotification) {
      return false
    }
    if (this === other) {
      return true
    }
    return LayrzBlePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class LayrzBlePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtStatus.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtDevice.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtManufacturerData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtServiceData.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtService.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtCharacteristic.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BtCharacteristicNotification.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BtStatus -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BtDevice -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is BtManufacturerData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is BtServiceData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is BtService -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is BtCharacteristic -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BtCharacteristicNotification -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LayrzBlePlatformChannel {
  fun getStatuses(callback: (Result<BtStatus>) -> Unit)
  fun checkCapabilities(callback: (Result<Boolean>) -> Unit)
  fun checkScanPermissions(callback: (Result<Boolean>) -> Unit)
  fun checkAdvertisePermissions(callback: (Result<Boolean>) -> Unit)
  fun startScan(macAddress: String?, servicesUuids: List<String>?, callback: (Result<Boolean>) -> Unit)
  fun stopScan(macAddress: String?, callback: (Result<Boolean>) -> Unit)
  fun connect(macAddress: String, callback: (Result<Boolean>) -> Unit)
  fun disconnect(macAddress: String?, callback: (Result<Boolean>) -> Unit)
  fun setMtu(macAddress: String, mtu: Long, callback: (Result<Long?>) -> Unit)
  fun discoverServices(macAddress: String, callback: (Result<List<BtService>>) -> Unit)
  fun readCharacteristic(macAddress: String, serviceUuid: String, characteristicUuid: String, callback: (Result<ByteArray>) -> Unit)
  fun writeCharacteristic(macAddress: String, serviceUuid: String, characteristicUuid: String, payload: ByteArray, withResponse: Boolean, callback: (Result<Boolean>) -> Unit)
  fun startNotify(macAddress: String, serviceUuid: String, characteristicUuid: String, callback: (Result<Boolean>) -> Unit)
  fun stopNotify(macAddress: String, serviceUuid: String, characteristicUuid: String, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by LayrzBlePlatformChannel. */
    val codec: MessageCodec<Any?> by lazy {
      LayrzBlePigeonCodec()
    }
    /** Sets up an instance of `LayrzBlePlatformChannel` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LayrzBlePlatformChannel?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.getStatuses$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getStatuses{ result: Result<BtStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkCapabilities{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkScanPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkScanPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.checkAdvertisePermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkAdvertisePermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String?
            val servicesUuidsArg = args[1] as List<String>?
            api.startScan(macAddressArg, servicesUuidsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.stopScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String?
            api.stopScan(macAddressArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            api.connect(macAddressArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String?
            api.disconnect(macAddressArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.setMtu$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            val mtuArg = args[1] as Long
            api.setMtu(macAddressArg, mtuArg) { result: Result<Long?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.discoverServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            api.discoverServices(macAddressArg) { result: Result<List<BtService>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.readCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            api.readCharacteristic(macAddressArg, serviceUuidArg, characteristicUuidArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.writeCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            val payloadArg = args[3] as ByteArray
            val withResponseArg = args[4] as Boolean
            api.writeCharacteristic(macAddressArg, serviceUuidArg, characteristicUuidArg, payloadArg, withResponseArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.startNotify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            api.startNotify(macAddressArg, serviceUuidArg, characteristicUuidArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_ble.LayrzBlePlatformChannel.stopNotify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val macAddressArg = args[0] as String
            val serviceUuidArg = args[1] as String
            val characteristicUuidArg = args[2] as String
            api.stopNotify(macAddressArg, serviceUuidArg, characteristicUuidArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzBlePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzBlePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class LayrzBleCallbackChannel(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LayrzBleCallbackChannel. */
    val codec: MessageCodec<Any?> by lazy {
      LayrzBlePigeonCodec()
    }
  }
  fun onScanResult(deviceArg: BtDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBluetoothOn(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onBluetoothOn$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBluetoothOff(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onBluetoothOff$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onScanStarted(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanStarted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onScanStopped(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onScanStopped$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onConnected(deviceArg: BtDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onConnected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDisconnected(deviceArg: BtDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onDisconnected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onCharacteristicUpdate(notificationArg: BtCharacteristicNotification, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_ble.LayrzBleCallbackChannel.onCharacteristicUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(notificationArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzBlePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
